### ISSUE TITLE
Install and Quick Start Errors 

### ISSUE THREAD

**Issue by AlohaPropolis** [balabanmetin/uDance#3]
My initial exposure to uDance installation and quick start was a little rocky. It’s seems the install.sh file creates a python 3.8 conda environment while in fact a version 3.9 is required. Also the quick start command line file uDANCE.smk does not exist it should read udance.smk. Thanks

**Comment by balabanmetin** [comment]
Thanks for the feedback. I fixed the README file increased required Python version to 3.9.
