### ISSUE TITLE
Execution is successful. But the generated nwk file is empty.

### ISSUE THREAD

**Issue by nimua** [balabanmetin/uDance#7]
[udance.log](https://github.com/balabanmetin/uDance/files/13405267/udance.log)
Hi, I generated the alignment file through MUSCLE. No error is reported, the nwk file is generated, but it is an empty file.

**Comment by nimua** [comment]
[2023-11-20T085747.049750.snakemake.log](https://github.com/balabanmetin/uDance/files/13468721/2023-11-20T085747.049750.snakemake.log)
[snakemake_stdout.log](https://github.com/balabanmetin/uDance/files/13468752/snakemake_stdout.log)
[astral.incremental.log](https://github.com/balabanmetin/uDance/files/13468727/astral.incremental.log)

Hi, 
astral.incremental.log exist. And I tried test data, it worked well.

**Comment by nimua** [comment]
muscle_313/output/backbone.nwk  7 species
muscle_313/output/placement/backbone.fa 7 species
muscle_313/output/placement/query.fa 209 species
muscle_313/output/placement/backbone.tree 7 species

The only content of the file color_spanning_tree.nwk is:
[&R] -1;

**Comment by nimua** [comment]
[285L.fasta.txt](https://github.com/balabanmetin/uDance/files/13468909/285L.fasta.txt)
This is one of the alignment file of my data. I also think it's a data problem, but I don't know where the problem is.

**Comment by balabanmetin** [comment]
Your alignments mostly consist of duplicates. There is almost no phylogenetic signal. Nearly all input sequences have the same sequence in all genes. uDance is not designed to deal with this kind of data. I would personally use the concatenation approach: Concatenate all the genes, remove duplicates (keep a representative for each duplicate cluster), run raxml or iqtree on the representatives, and finally map duplicates back to representatives.

**Comment by nimua** [comment]
Thank you for your advice.
I used all genes. Some of them may have very small differences between species. So I tried again with only one gene that often used for making phylogenetic tree of that species. But I got an error:
[udance.log](https://github.com/balabanmetin/uDance/files/13469083/udance.log)
[2023-11-27T101756.938253.snakemake.log](https://github.com/balabanmetin/uDance/files/13469088/2023-11-27T101756.938253.snakemake.log)
