### ISSUE TITLE
The number of taxa in the generated tree is smaller than the number of input taxa

### ISSUE THREAD

**Issue by nimua** [balabanmetin/uDance#8]
Hi, 
There are 334 taxa in my input data, but udance.maxqs.nwk only contains about 270 taxa. I don't understand the reason for the decrease in numbers.

[udance.log](https://github.com/balabanmetin/uDance/files/13647899/udance.log)

I used this config:

backbone: "de-novo"
mainlines_config:
  # target number of taxa
  n: 334
  # concatenation alignment length
  length: 5000

**Comment by balabanmetin** [comment]
Species can be removed for several reasons such as QC, being a duplicate, or being unplaceable, something we discussed in our manuscript. The good thing is the unplaceable sequences can be replaced. Run a second iteration of udance and input your first output tree as the backbone tree. Does that make sense?

**Comment by nimua** [comment]
Thank you. That make sense.
